defaults: &defaults
  paginate_per_page: 2
  asset_host: "http://localhost:9000"
  host: "http://localhost:9000"
  origin: "http://localhost:9000/v1"
  allow_origin: "http://ffffff.com:3001,http://localhost:3000"


development:
  <<: *defaults


test:
  <<: *defaults

production:
  <<: *defaults
